FROM node:20-alpine

WORKDIR /app

# Install development tools
RUN apk add --no-cache dumb-init python3 make g++

# Copy package files
COPY package*.json ./
COPY prisma ./prisma

# Install dependencies
RUN npm install

# Generate Prisma client
RUN npx prisma generate

EXPOSE 3001

ENTRYPOINT ["dumb-init", "--"]

CMD ["npm", "run", "dev"]
